name: Deploy

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

permissions:
  contents: 'write'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: gcp-cloudrun

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          access_token_lifetime: '300s'

      - name: 'Login to Artifact Registry'
        uses: 'docker/login-action@v1'
        with:
          registry: 'us-central1-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: 'Build, push, and deploy'
        run: |
          ./build.sh
          ./push.sh
          ./deploy.sh
